apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: sample-app
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: sample-app
    apps.tanzu.vmware.com/has-tests: true
    tanzu.app.live.view: true
    tanzu.app.live.view.application.flavors: steeltoe
    tanzu.app.live.view.application.name: sample-app
spec:
  params:
    - name: annotations
      value: 
        autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: https://github.com/hananiel/steeltoe-weatherforecast
      ref:
        branch: alv
